package com.vinaynalavade.expensetracker.presentation.recurring

import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.text.KeyboardOptions
import androidx.compose.foundation.verticalScroll
import androidx.compose.material3.AlertDialog
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.OutlinedTextField
import androidx.compose.material3.Switch
import androidx.compose.material3.Tab
import androidx.compose.material3.TabRow
import androidx.compose.material3.Text
import androidx.compose.material3.TextButton
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.input.ImeAction
import androidx.compose.ui.text.input.KeyboardType
import androidx.compose.ui.unit.dp
import com.vinaynalavade.expensetracker.core.model.Amount
import com.vinaynalavade.expensetracker.core.model.Currency
import com.vinaynalavade.expensetracker.core.util.AmountInputFormatter
import com.vinaynalavade.expensetracker.domain.model.Category
import com.vinaynalavade.expensetracker.domain.model.PaymentMethod
import com.vinaynalavade.expensetracker.domain.model.RecurrenceFrequency
import com.vinaynalavade.expensetracker.domain.model.RecurringTransaction
import com.vinaynalavade.expensetracker.domain.model.TransactionType
import com.vinaynalavade.expensetracker.presentation.components.PaymentMethodSelector
import com.vinaynalavade.expensetracker.presentation.entry.components.AmountVisualTransformation
import com.vinaynalavade.expensetracker.presentation.entry.components.CategorySelector
import com.vinaynalavade.expensetracker.presentation.theme.ButtonShape
import com.vinaynalavade.expensetracker.presentation.theme.CardShape
import com.vinaynalavade.expensetracker.presentation.theme.DialogShape
import com.vinaynalavade.expensetracker.presentation.theme.LocalCurrency
import com.vinaynalavade.expensetracker.presentation.theme.spacing
import androidx.compose.foundation.layout.widthIn
import androidx.compose.ui.window.DialogProperties

@Composable
fun AddEditRecurringDialog(
    itemToEdit: RecurringTransaction?,
    availableCategories: List<Category>,
    onDismiss: () -> Unit,
    onSave: (RecurringTransaction) -> Unit,
    currency: Currency = LocalCurrency.current
) {
    var title by remember(itemToEdit) { mutableStateOf(itemToEdit?.title ?: "") }
    var titleError by remember { mutableStateOf<String?>(null) }

    var amountText by remember(itemToEdit) { mutableStateOf(itemToEdit?.amount?.toInputString(currency) ?: "") }
    var amountError by remember { mutableStateOf<String?>(null) }

    var selectedType by remember(itemToEdit) { mutableStateOf(itemToEdit?.type ?: TransactionType.EXPENSE) }
    var selectedCategory by remember(itemToEdit) {
        mutableStateOf(itemToEdit?.category ?: availableCategories.firstOrNull { it.type == selectedType })
    }
    var selectedPaymentMethod by remember(itemToEdit) {
        mutableStateOf(itemToEdit?.paymentMethod ?: PaymentMethod.CASH)
    }
    var selectedFrequency by remember(itemToEdit) { mutableStateOf(itemToEdit?.frequency ?: RecurrenceFrequency.MONTHLY) }

    var dayOfMonthText by remember(itemToEdit) { mutableStateOf(itemToEdit?.dayOfMonth?.toString() ?: "1") }
    var dayOfMonthError by remember { mutableStateOf<String?>(null) }

    var isAutoGenerated by remember(itemToEdit) { mutableStateOf(itemToEdit?.isAutoGenerated ?: true) }
    var reminderDaysBefore by remember(itemToEdit) { mutableStateOf(itemToEdit?.reminderDaysBefore?.toString() ?: "1") }

    val filteredCategories = availableCategories.filter { it.type == selectedType }

    AlertDialog(
        onDismissRequest = onDismiss,
        properties = DialogProperties(
            dismissOnBackPress = true,
            dismissOnClickOutside = true,
            usePlatformDefaultWidth = false
        ),
        modifier = Modifier
            .fillMaxWidth(0.95f)
            .widthIn(max = 500.dp),
        title = {
            Text(
                text = if (itemToEdit == null) "Schedule Recurring / EMI" else "Edit Recurring Transaction",
                style = MaterialTheme.typography.titleMedium,
                fontWeight = FontWeight.Bold
            )
        },
        text = {
            Column(
                modifier = Modifier
                    .fillMaxWidth()
                    .verticalScroll(rememberScrollState())
            ) {
                // Type Tabs
                TabRow(selectedTabIndex = selectedType.ordinal) {
                    TransactionType.entries.forEach { type ->
                        Tab(
                            selected = selectedType == type,
                            onClick = {
                                selectedType = type
                                selectedCategory = availableCategories.firstOrNull { it.type == type }
                            },
                            text = { Text(type.displayName) }
                        )
                    }
                }

                Spacer(modifier = Modifier.height(MaterialTheme.spacing.md))

                // Title Input
                OutlinedTextField(
                    value = title,
                    onValueChange = {
                        title = it
                        if (it.isNotBlank()) titleError = null
                    },
                    label = { Text("Title (e.g. Monthly Salary, Home Rent, Car EMI)") },
                    isError = titleError != null,
                    supportingText = titleError?.let { err ->
                        { Text(text = err, color = MaterialTheme.colorScheme.error) }
                    },
                    singleLine = true,
                    shape = ButtonShape,
                    modifier = Modifier.fillMaxWidth()
                )

                Spacer(modifier = Modifier.height(MaterialTheme.spacing.sm))

                // Amount Input
                OutlinedTextField(
                    value = amountText,
                    onValueChange = { input ->
                        val sanitized = AmountInputFormatter.sanitizeAmountInput(input, currency.decimalDigits)
                        amountText = sanitized
                        if (sanitized.isNotBlank()) amountError = null
                    },
                    visualTransformation = AmountVisualTransformation(),
                    label = { Text("Amount (${currency.symbol})") },
                    isError = amountError != null,
                    supportingText = amountError?.let { err ->
                        { Text(text = err, color = MaterialTheme.colorScheme.error) }
                    },
                    keyboardOptions = KeyboardOptions(keyboardType = KeyboardType.Decimal),
                    singleLine = true,
                    shape = ButtonShape,
                    modifier = Modifier.fillMaxWidth()
                )

                Spacer(modifier = Modifier.height(MaterialTheme.spacing.md))

                // Category Selector
                CategorySelector(
                    categories = filteredCategories,
                    selectedCategory = selectedCategory,
                    onCategorySelect = { selectedCategory = it }
                )

                Spacer(modifier = Modifier.height(MaterialTheme.spacing.md))

                // Payment Method Selector
                PaymentMethodSelector(
                    selectedMethod = selectedPaymentMethod,
                    onMethodSelect = { selectedPaymentMethod = it },
                    isCompact = true,
                    horizontalPadding = 0.dp
                )

                Spacer(modifier = Modifier.height(MaterialTheme.spacing.md))

                // Day of Month Input
                OutlinedTextField(
                    value = dayOfMonthText,
                    onValueChange = { input ->
                        val digitsOnly = input.filter { it.isDigit() }
                        if (digitsOnly.length <= 2) {
                            dayOfMonthText = digitsOnly
                            val num = digitsOnly.toIntOrNull()
                            dayOfMonthError = when {
                                digitsOnly.isEmpty() -> null
                                num == null || num !in 1..31 -> "Day must be between 1 and 31."
                                else -> null
                            }
                        }
                    },
                    label = { Text("Day of Month (1 - 31)") },
                    placeholder = { Text("e.g. 5, 15, 31") },
                    isError = dayOfMonthError != null,
                    supportingText = dayOfMonthError?.let { err ->
                        { Text(text = err, color = MaterialTheme.colorScheme.error) }
                    },
                    keyboardOptions = KeyboardOptions(
                        keyboardType = KeyboardType.Number,
                        imeAction = ImeAction.Done
                    ),
                    singleLine = true,
                    shape = ButtonShape,
                    modifier = Modifier.fillMaxWidth()
                )

                Spacer(modifier = Modifier.height(MaterialTheme.spacing.md))

                // Auto-generate Switch
                Row(
                    modifier = Modifier.fillMaxWidth(),
                    horizontalArrangement = Arrangement.SpaceBetween,
                    verticalAlignment = Alignment.CenterVertically
                ) {
                    Column(modifier = Modifier.weight(1f)) {
                        Text(text = "Auto-create Transaction", style = MaterialTheme.typography.bodyMedium, fontWeight = FontWeight.SemiBold)
                        Text(text = "Automatically records to ledger on due date", style = MaterialTheme.typography.bodySmall, color = MaterialTheme.colorScheme.onSurfaceVariant)
                    }
                    Switch(checked = isAutoGenerated, onCheckedChange = { isAutoGenerated = it })
                }
            }
        },
        confirmButton = {
            TextButton(
                onClick = {
                    var hasError = false

                    if (title.isBlank()) {
                        titleError = "Title cannot be empty."
                        hasError = true
                    } else {
                        titleError = null
                    }

                    val parsedAmount = Amount.fromStringOrNull(amountText, currency)
                    if (parsedAmount == null || parsedAmount.isZero || parsedAmount.isNegative) {
                        amountError = "Enter a valid amount."
                        hasError = true
                    } else {
                        amountError = null
                    }

                    val dayNum = dayOfMonthText.toIntOrNull()
                    if (dayNum == null || dayNum !in 1..31) {
                        dayOfMonthError = if (dayOfMonthText.isBlank()) {
                            "Enter a valid day of the month."
                        } else {
                            "Day must be between 1 and 31."
                        }
                        hasError = true
                    } else {
                        dayOfMonthError = null
                    }

                    val cat = selectedCategory
                    if (cat == null) {
                        hasError = true
                    }

                    if (!hasError && parsedAmount != null && cat != null && dayNum != null) {
                        val now = System.currentTimeMillis()
                        val newItem = RecurringTransaction(
                            id = itemToEdit?.id ?: 0L,
                            title = title.trim(),
                            amount = parsedAmount,
                            type = selectedType,
                            category = cat,
                            paymentMethod = selectedPaymentMethod,
                            frequency = selectedFrequency,
                            dayOfMonth = dayNum,
                            startDate = itemToEdit?.startDate ?: now,
                            endDate = itemToEdit?.endDate,
                            isEnabled = itemToEdit?.isEnabled ?: true,
                            isAutoGenerated = isAutoGenerated,
                            reminderDaysBefore = reminderDaysBefore.toIntOrNull(),
                            lastGeneratedDate = itemToEdit?.lastGeneratedDate,
                            createdAt = itemToEdit?.createdAt ?: now,
                            updatedAt = now
                        )
                        onSave(newItem)
                    }
                }
            ) {
                Text(text = "Save", fontWeight = FontWeight.Bold)
            }
        },
        dismissButton = {
            TextButton(onClick = onDismiss) {
                Text(text = "Cancel")
            }
        },
        shape = DialogShape,
        containerColor = MaterialTheme.colorScheme.surface
    )
}
