package com.vinaynalavade.expensetracker

import com.vinaynalavade.expensetracker.core.model.Amount
import com.vinaynalavade.expensetracker.core.result.AppError
import com.vinaynalavade.expensetracker.core.result.AppResult
import com.vinaynalavade.expensetracker.core.utils.DateTimeUtils
import com.vinaynalavade.expensetracker.domain.model.Category
import com.vinaynalavade.expensetracker.domain.model.PaymentMethod
import com.vinaynalavade.expensetracker.domain.model.RecurrenceFrequency
import com.vinaynalavade.expensetracker.domain.model.RecurringTransaction
import com.vinaynalavade.expensetracker.domain.model.TransactionType
import com.vinaynalavade.expensetracker.domain.repository.RecurringTransactionRepository
import com.vinaynalavade.expensetracker.domain.usecase.SaveRecurringTransactionUseCase
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.flowOf
import kotlinx.coroutines.runBlocking
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertTrue
import org.junit.Before
import org.junit.Test
import java.time.LocalDate
import java.time.YearMonth

class RecurringEmiDayOfMonthTest {

    private val sampleCategory = Category(
        id = 1L,
        name = "Rent / EMI",
        iconName = "home",
        colorHex = "#FF5722",
        type = TransactionType.EXPENSE
    )

    private lateinit var fakeRepo: FakeRecurringRepository
    private lateinit var saveUseCase: SaveRecurringTransactionUseCase

    @Before
    fun setUp() {
        fakeRepo = FakeRecurringRepository()
        saveUseCase = SaveRecurringTransactionUseCase(fakeRepo)
    }

    private fun createEmi(day: Int, id: Long = 0L): RecurringTransaction {
        return RecurringTransaction(
            id = id,
            title = "Car Loan EMI",
            amount = Amount(2500000L), // ₹25,000
            type = TransactionType.EXPENSE,
            category = sampleCategory,
            paymentMethod = PaymentMethod.ACCOUNT,
            frequency = RecurrenceFrequency.MONTHLY,
            dayOfMonth = day,
            isEnabled = true,
            isAutoGenerated = true
        )
    }

    // ─── 1. Input & Range Validation Tests ───

    @Test
    fun testValidDaysAreAccepted() = runBlocking {
        val validDays = listOf(1, 15, 28, 29, 30, 31)
        for (day in validDays) {
            val emi = createEmi(day)
            val result = saveUseCase(emi)
            assertTrue("Day $day should be accepted", result is AppResult.Success)
        }
    }

    @Test
    fun testDayZeroIsRejected() = runBlocking {
        val emi = createEmi(0)
        val result = saveUseCase(emi)
        assertTrue(result is AppResult.Error)
        val error = (result as AppResult.Error).error
        assertTrue(error is AppError.ValidationError)
        assertEquals("dayOfMonth", (error as AppError.ValidationError).field)
    }

    @Test
    fun testDay32IsRejected() = runBlocking {
        val emi = createEmi(32)
        val result = saveUseCase(emi)
        assertTrue(result is AppResult.Error)
        val error = (result as AppResult.Error).error
        assertTrue(error is AppError.ValidationError)
        assertEquals("dayOfMonth", (error as AppError.ValidationError).field)
    }

    @Test
    fun testNegativeDayIsRejected() = runBlocking {
        val emi = createEmi(-5)
        val result = saveUseCase(emi)
        assertTrue(result is AppResult.Error)
        val error = (result as AppResult.Error).error
        assertTrue(error is AppError.ValidationError)
        assertEquals("dayOfMonth", (error as AppError.ValidationError).field)
    }

    @Test
    fun testEmptyOrInvalidAmountRejected() = runBlocking {
        val emi = createEmi(15).copy(amount = Amount(0L))
        val result = saveUseCase(emi)
        assertTrue(result is AppResult.Error)
    }

    @Test
    fun testBlankTitleRejected() = runBlocking {
        val emi = createEmi(15).copy(title = "   ")
        val result = saveUseCase(emi)
        assertTrue(result is AppResult.Error)
    }

    // ─── 2. Calendar Scheduling & Clamping Tests ───

    @Test
    fun testDay31SchedulesJanuary31() {
        val jan2026 = YearMonth.of(2026, 1)
        val scheduledDay = DateTimeUtils.getScheduledDayOfMonth(31, jan2026)
        val scheduledDate = DateTimeUtils.getScheduledDate(31, jan2026)

        assertEquals(31, scheduledDay)
        assertEquals(LocalDate.of(2026, 1, 31), scheduledDate)
    }

    @Test
    fun testDay31SchedulesFebruary28InNormalYear() {
        val feb2026 = YearMonth.of(2026, 2)
        val scheduledDay = DateTimeUtils.getScheduledDayOfMonth(31, feb2026)
        val scheduledDate = DateTimeUtils.getScheduledDate(31, feb2026)

        assertEquals(28, scheduledDay)
        assertEquals(LocalDate.of(2026, 2, 28), scheduledDate)
    }

    @Test
    fun testDay31SchedulesFebruary29InLeapYear() {
        val feb2024 = YearMonth.of(2024, 2)
        val scheduledDay = DateTimeUtils.getScheduledDayOfMonth(31, feb2024)
        val scheduledDate = DateTimeUtils.getScheduledDate(31, feb2024)

        assertEquals(29, scheduledDay)
        assertEquals(LocalDate.of(2024, 2, 29), scheduledDate)
    }

    @Test
    fun testDay31SchedulesApril30() {
        val apr2026 = YearMonth.of(2026, 4)
        val scheduledDay = DateTimeUtils.getScheduledDayOfMonth(31, apr2026)
        val scheduledDate = DateTimeUtils.getScheduledDate(31, apr2026)

        assertEquals(30, scheduledDay)
        assertEquals(LocalDate.of(2026, 4, 30), scheduledDate)
    }

    @Test
    fun testDay29SchedulesFebruary28InNonLeapYear() {
        val feb2026 = YearMonth.of(2026, 2)
        val scheduledDay = DateTimeUtils.getScheduledDayOfMonth(29, feb2026)
        val scheduledDate = DateTimeUtils.getScheduledDate(29, feb2026)

        assertEquals(28, scheduledDay)
        assertEquals(LocalDate.of(2026, 2, 28), scheduledDate)
    }

    @Test
    fun testDay29SchedulesFebruary29InLeapYear() {
        val feb2024 = YearMonth.of(2024, 2)
        val scheduledDay = DateTimeUtils.getScheduledDayOfMonth(29, feb2024)
        val scheduledDate = DateTimeUtils.getScheduledDate(29, feb2024)

        assertEquals(29, scheduledDay)
        assertEquals(LocalDate.of(2024, 2, 29), scheduledDate)
    }

    @Test
    fun testDay30SchedulesFebruaryCorrectly() {
        val feb2026 = YearMonth.of(2026, 2)
        val feb2024 = YearMonth.of(2024, 2)

        assertEquals(28, DateTimeUtils.getScheduledDayOfMonth(30, feb2026))
        assertEquals(29, DateTimeUtils.getScheduledDayOfMonth(30, feb2024))
    }

    @Test
    fun testMonthTransitionsAcrossEntireYearForDay31() {
        // Month lengths for 2026 (normal year)
        val expectedDays = listOf(
            Pair(YearMonth.of(2026, 1), 31),
            Pair(YearMonth.of(2026, 2), 28),
            Pair(YearMonth.of(2026, 3), 31),
            Pair(YearMonth.of(2026, 4), 30),
            Pair(YearMonth.of(2026, 5), 31),
            Pair(YearMonth.of(2026, 6), 30),
            Pair(YearMonth.of(2026, 7), 31),
            Pair(YearMonth.of(2026, 8), 31),
            Pair(YearMonth.of(2026, 9), 30),
            Pair(YearMonth.of(2026, 10), 31),
            Pair(YearMonth.of(2026, 11), 30),
            Pair(YearMonth.of(2026, 12), 31)
        )

        for ((ym, expectedDay) in expectedDays) {
            val actualDay = DateTimeUtils.getScheduledDayOfMonth(31, ym)
            assertEquals("Month ${ym.month} should have scheduled day $expectedDay", expectedDay, actualDay)
        }
    }

    @Test
    fun testYearTransitionMaintainsCorrectDay() {
        val dec2025 = YearMonth.of(2025, 12)
        val jan2026 = YearMonth.of(2026, 1)

        assertEquals(31, DateTimeUtils.getScheduledDayOfMonth(31, dec2025))
        assertEquals(31, DateTimeUtils.getScheduledDayOfMonth(31, jan2026))
    }

    // ─── 3. Editing & Persistence Tests ───

    @Test
    fun testEditingExistingEmiUpdatesDayOfMonth() = runBlocking {
        val initialEmi = createEmi(5)
        val insertResult = saveUseCase(initialEmi)
        assertTrue(insertResult is AppResult.Success)
        val id = (insertResult as AppResult.Success).data

        // Edit from day 5 to day 15
        val updatedEmi = fakeRepo.items[id]!!.copy(dayOfMonth = 15)
        val updateResult = saveUseCase(updatedEmi)
        assertTrue(updateResult is AppResult.Success)

        val persisted = fakeRepo.items[id]
        assertEquals(15, persisted?.dayOfMonth)
    }

    @Test
    fun testEditingToDay31PersistsCleanly() = runBlocking {
        val initialEmi = createEmi(28)
        val insertResult = saveUseCase(initialEmi)
        val id = (insertResult as AppResult.Success).data

        // Change from 28 to 31
        val updatedEmi = fakeRepo.items[id]!!.copy(dayOfMonth = 31)
        saveUseCase(updatedEmi)

        val persisted = fakeRepo.items[id]
        assertEquals(31, persisted?.dayOfMonth)
    }

    @Test
    fun testConfiguredDayRemains31AfterClampedOccurrence() = runBlocking {
        // When configured for 31, the stored model retains 31 even if scheduled for Feb 28
        val emi = createEmi(31)
        saveUseCase(emi)

        val feb2026 = YearMonth.of(2026, 2)
        val occurrenceDate = DateTimeUtils.getScheduledDate(emi.dayOfMonth, feb2026)

        assertEquals(LocalDate.of(2026, 2, 28), occurrenceDate)
        assertEquals(31, emi.dayOfMonth) // Model configuration never mutates to 28
    }

    // ─── 4. First-Occurrence Due Calculation Tests (Issue 2) ───

    private fun createEntity(
        dayOfMonth: Int,
        startDate: LocalDate,
        lastGeneratedDate: LocalDate? = null,
        endDate: LocalDate? = null,
        frequency: String = "MONTHLY"
    ): com.vinaynalavade.expensetracker.data.local.entity.RecurringTransactionEntity {
        val zone = java.time.ZoneId.systemDefault()
        return com.vinaynalavade.expensetracker.data.local.entity.RecurringTransactionEntity(
            id = 1L,
            title = "Test EMI",
            amountSubunits = 500000L,
            type = "EXPENSE",
            categoryId = 1L,
            paymentMethod = "BANK_ACCOUNT",
            frequency = frequency,
            dayOfMonth = dayOfMonth,
            dayOfWeek = 1,
            startDate = startDate.atStartOfDay(zone).toInstant().toEpochMilli(),
            endDate = endDate?.atStartOfDay(zone)?.toInstant()?.toEpochMilli(),
            isEnabled = true,
            isAutoGenerated = true,
            reminderDaysBefore = 1,
            lastGeneratedDate = lastGeneratedDate?.atStartOfDay(zone)?.toInstant()?.toEpochMilli(),
            createdAt = startDate.atStartOfDay(zone).toInstant().toEpochMilli(),
            updatedAt = startDate.atStartOfDay(zone).toInstant().toEpochMilli()
        )
    }

    @Test
    fun testScenario1_CreatedOnAug23_ConfiguredDay3_NotDueOnAug23() {
        val repo = com.vinaynalavade.expensetracker.data.repository.RecurringTransactionRepositoryImpl(
            FakeRecurringDao(),
            FakeTxDao()
        )
        val entity = createEntity(dayOfMonth = 3, startDate = LocalDate.of(2026, 8, 23))

        // Check on creation day (Aug 23)
        assertFalse(repo.checkIfDue(entity, LocalDate.of(2026, 8, 23)))
        // Check on Aug 31
        assertFalse(repo.checkIfDue(entity, LocalDate.of(2026, 8, 31)))
        // Check on Sept 2
        assertFalse(repo.checkIfDue(entity, LocalDate.of(2026, 9, 2)))
        // Check on Sept 3 (Due Date!)
        assertTrue(repo.checkIfDue(entity, LocalDate.of(2026, 9, 3)))
    }

    @Test
    fun testScenario2_CreatedOnAug2_ConfiguredDay3_DueOnAug3() {
        val repo = com.vinaynalavade.expensetracker.data.repository.RecurringTransactionRepositoryImpl(
            FakeRecurringDao(),
            FakeTxDao()
        )
        val entity = createEntity(dayOfMonth = 3, startDate = LocalDate.of(2026, 8, 2))

        // Check on creation day (Aug 2) -> Not due
        assertFalse(repo.checkIfDue(entity, LocalDate.of(2026, 8, 2)))
        // Check on Aug 3 -> Due!
        assertTrue(repo.checkIfDue(entity, LocalDate.of(2026, 8, 3)))
    }

    @Test
    fun testScenario3_CreatedOnAug3_ConfiguredDay3_DueOnAug3() {
        val repo = com.vinaynalavade.expensetracker.data.repository.RecurringTransactionRepositoryImpl(
            FakeRecurringDao(),
            FakeTxDao()
        )
        val entity = createEntity(dayOfMonth = 3, startDate = LocalDate.of(2026, 8, 3))

        // Check on creation day (Aug 3) -> Due!
        assertTrue(repo.checkIfDue(entity, LocalDate.of(2026, 8, 3)))
    }

    @Test
    fun testScenario4_CreatedOnAug3_ConfiguredDay2_NotDueUntilSept2() {
        val repo = com.vinaynalavade.expensetracker.data.repository.RecurringTransactionRepositoryImpl(
            FakeRecurringDao(),
            FakeTxDao()
        )
        val entity = createEntity(dayOfMonth = 2, startDate = LocalDate.of(2026, 8, 3))

        // Check on creation day (Aug 3) -> Not due (Day 2 in Aug has passed)
        assertFalse(repo.checkIfDue(entity, LocalDate.of(2026, 8, 3)))
        // Check on Aug 20 -> Not due
        assertFalse(repo.checkIfDue(entity, LocalDate.of(2026, 8, 20)))
        // Check on Sept 1 -> Not due
        assertFalse(repo.checkIfDue(entity, LocalDate.of(2026, 9, 1)))
        // Check on Sept 2 -> Due!
        assertTrue(repo.checkIfDue(entity, LocalDate.of(2026, 9, 2)))
    }

    @Test
    fun testScenario5_CreatedOnMar15_ConfiguredDay31_DueOnApr30() {
        val repo = com.vinaynalavade.expensetracker.data.repository.RecurringTransactionRepositoryImpl(
            FakeRecurringDao(),
            FakeTxDao()
        )
        // Created Mar 15 with day 31. First occurrence Mar 31.
        val entity = createEntity(dayOfMonth = 31, startDate = LocalDate.of(2026, 3, 15))
        assertTrue(repo.checkIfDue(entity, LocalDate.of(2026, 3, 31)))

        // If generated on Mar 31, next is Apr 30
        val generatedEntity = entity.copy(
            lastGeneratedDate = LocalDate.of(2026, 3, 31).atStartOfDay(java.time.ZoneId.systemDefault()).toInstant().toEpochMilli()
        )
        assertFalse(repo.checkIfDue(generatedEntity, LocalDate.of(2026, 4, 29)))
        assertTrue(repo.checkIfDue(generatedEntity, LocalDate.of(2026, 4, 30)))
    }

    @Test
    fun testScenario6_ConfiguredDay31_FebNormalYear_DueOnFeb28() {
        val repo = com.vinaynalavade.expensetracker.data.repository.RecurringTransactionRepositoryImpl(
            FakeRecurringDao(),
            FakeTxDao()
        )
        val entity = createEntity(dayOfMonth = 31, startDate = LocalDate.of(2026, 2, 1))

        assertFalse(repo.checkIfDue(entity, LocalDate.of(2026, 2, 27)))
        assertTrue(repo.checkIfDue(entity, LocalDate.of(2026, 2, 28)))
    }

    @Test
    fun testScenario7_ConfiguredDay31_FebLeapYear_DueOnFeb29() {
        val repo = com.vinaynalavade.expensetracker.data.repository.RecurringTransactionRepositoryImpl(
            FakeRecurringDao(),
            FakeTxDao()
        )
        val entity = createEntity(dayOfMonth = 31, startDate = LocalDate.of(2024, 2, 1))

        assertFalse(repo.checkIfDue(entity, LocalDate.of(2024, 2, 28)))
        assertTrue(repo.checkIfDue(entity, LocalDate.of(2024, 2, 29)))
    }

    @Test
    fun testScenario8_NoDuplicateGenerationInSamePeriod() {
        val repo = com.vinaynalavade.expensetracker.data.repository.RecurringTransactionRepositoryImpl(
            FakeRecurringDao(),
            FakeTxDao()
        )
        // Generated on Aug 3
        val entity = createEntity(
            dayOfMonth = 3,
            startDate = LocalDate.of(2026, 8, 1),
            lastGeneratedDate = LocalDate.of(2026, 8, 3)
        )

        // Same day restart
        assertFalse(repo.checkIfDue(entity, LocalDate.of(2026, 8, 3)))
        // Subsequent days in August
        assertFalse(repo.checkIfDue(entity, LocalDate.of(2026, 8, 4)))
        assertFalse(repo.checkIfDue(entity, LocalDate.of(2026, 8, 23)))
        assertFalse(repo.checkIfDue(entity, LocalDate.of(2026, 8, 31)))

        // Next month (Sept 3) -> Due!
        assertTrue(repo.checkIfDue(entity, LocalDate.of(2026, 9, 3)))
    }

    @Test
    fun testScenario9_RespectsEndDateBoundary() {
        val repo = com.vinaynalavade.expensetracker.data.repository.RecurringTransactionRepositoryImpl(
            FakeRecurringDao(),
            FakeTxDao()
        )
        val entity = createEntity(
            dayOfMonth = 3,
            startDate = LocalDate.of(2026, 8, 1),
            endDate = LocalDate.of(2026, 8, 31)
        )

        // Due on Aug 3
        assertTrue(repo.checkIfDue(entity, LocalDate.of(2026, 8, 3)))
        // In September, past end date -> Not due
        assertFalse(repo.checkIfDue(entity, LocalDate.of(2026, 9, 3)))
    }

    // ─── Fake DAOs ───

    private class FakeRecurringDao : com.vinaynalavade.expensetracker.data.local.dao.RecurringTransactionDao {
        val items = mutableListOf<com.vinaynalavade.expensetracker.data.local.entity.RecurringWithCategory>()
        override fun getAllRecurringWithCategory(): Flow<List<com.vinaynalavade.expensetracker.data.local.entity.RecurringWithCategory>> = flowOf(items)
        override fun getRecurringWithCategoryById(id: Long): Flow<com.vinaynalavade.expensetracker.data.local.entity.RecurringWithCategory?> = flowOf(items.find { it.recurring.id == id })
        override suspend fun getActiveRecurringTransactions(): List<com.vinaynalavade.expensetracker.data.local.entity.RecurringWithCategory> = items
        override suspend fun insertRecurringTransaction(entity: com.vinaynalavade.expensetracker.data.local.entity.RecurringTransactionEntity): Long = 1L
        override suspend fun insertRecurringTransactions(entities: List<com.vinaynalavade.expensetracker.data.local.entity.RecurringTransactionEntity>) {}
        override suspend fun updateRecurringTransaction(entity: com.vinaynalavade.expensetracker.data.local.entity.RecurringTransactionEntity) {}
        override suspend fun deleteRecurringTransactionById(id: Long) {}
        override suspend fun deleteAllRecurringTransactions() {}
    }

    private class FakeTxDao : com.vinaynalavade.expensetracker.data.local.dao.TransactionDao {
        override fun getAllTransactionsWithCategory(): Flow<List<com.vinaynalavade.expensetracker.data.local.entity.TransactionWithCategory>> = flowOf(emptyList())
        override fun getRecentTransactionsWithCategory(limit: Int): Flow<List<com.vinaynalavade.expensetracker.data.local.entity.TransactionWithCategory>> = flowOf(emptyList())
        override fun getTransactionWithCategoryById(id: Long): Flow<com.vinaynalavade.expensetracker.data.local.entity.TransactionWithCategory?> = flowOf(null)
        override suspend fun getTransactionByIdSuspend(id: Long): com.vinaynalavade.expensetracker.data.local.entity.TransactionEntity? = null
        override fun getTransactionsBetween(startDate: Long, endDate: Long): Flow<List<com.vinaynalavade.expensetracker.data.local.entity.TransactionWithCategory>> = flowOf(emptyList())
        override fun getTotalIncomeSubunits(): Flow<Long> = flowOf(0L)
        override fun getTotalExpenseSubunits(): Flow<Long> = flowOf(0L)
        override suspend fun insertTransaction(transaction: com.vinaynalavade.expensetracker.data.local.entity.TransactionEntity): Long = 1L
        override suspend fun insertTransactions(transactions: List<com.vinaynalavade.expensetracker.data.local.entity.TransactionEntity>) {}
        override suspend fun updateTransaction(transaction: com.vinaynalavade.expensetracker.data.local.entity.TransactionEntity) {}
        override suspend fun deleteTransactionById(id: Long) {}
        override suspend fun deleteAllTransactions() {}
    }

    // ─── Fake Repository ───

    private class FakeRecurringRepository : RecurringTransactionRepository {
        val items = mutableMapOf<Long, RecurringTransaction>()
        private var nextId = 1L

        override fun getRecurringTransactions(): Flow<List<RecurringTransaction>> =
            flowOf(items.values.toList())

        override fun getRecurringTransactionById(id: Long): Flow<RecurringTransaction?> =
            flowOf(items[id])

        override suspend fun insertRecurringTransaction(recurringTransaction: RecurringTransaction): AppResult<Long> {
            val id = nextId++
            items[id] = recurringTransaction.copy(id = id)
            return AppResult.Success(id)
        }

        override suspend fun updateRecurringTransaction(recurringTransaction: RecurringTransaction): AppResult<Unit> {
            items[recurringTransaction.id] = recurringTransaction
            return AppResult.Success(Unit)
        }

        override suspend fun deleteRecurringTransaction(id: Long): AppResult<Unit> {
            items.remove(id)
            return AppResult.Success(Unit)
        }

        override suspend fun processDueOccurrences(): AppResult<Int> {
            return AppResult.Success(0)
        }
    }
}
